# Generated by Django 4.0.3 on 2022-03-21 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('competitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='best_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.querytask'),
        ),
    ]
