# Generated by Django 4.0.3 on 2022-03-21 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('competitor', '0002_team_best_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='best_task',
        ),
        migrations.AddField(
            model_name='team',
            name='best_private_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_team', to='task.querytask'),
        ),
        migrations.AddField(
            model_name='team',
            name='best_public_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_team', to='task.querytask'),
        ),
    ]
