# Generated by Django 4.0.3 on 2022-03-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('competitor', '0003_remove_team_best_task_team_best_private_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='best_private_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_team', related_query_name='private_team', to='task.querytask'),
        ),
        migrations.AlterField(
            model_name='team',
            name='best_public_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_team', related_query_name='public_team', to='task.querytask'),
        ),
    ]
