# Generated by Django 4.0.3 on 2022-03-27 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0004_alter_team_best_private_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitor.team'),
        ),
    ]
