# Generated by Django 4.0.3 on 2022-03-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0004_alter_team_best_private_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='entry',
            field=models.IntegerField(null=True),
        ),
    ]
