# Generated by Django 4.0.3 on 2022-03-22 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0005_alter_competitor_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitor.team'),
        ),
    ]
