# Generated by Django 4.0.3 on 2022-03-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitor', '0005_team_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='entry',
            new_name='entries',
        ),
    ]
