# Generated by Django 4.0.3 on 2022-03-20 18:23

import competition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('upload_limit', models.IntegerField()),
                ('running_time_limit', models.IntegerField()),
                ('concurrent_limit', models.IntegerField(default=1)),
                ('end_time', models.DateTimeField()),
                ('competitor_info', models.FileField(upload_to=competition.models.get_upload_competitor_info_path)),
                ('private_sql', models.FileField(upload_to=competition.models.get_upload_private_path)),
                ('public_sql', models.FileField(upload_to=competition.models.get_upload_public_path)),
                ('reference_query', models.FileField(upload_to=competition.models.get_reference_query_path)),
                ('private_result', models.TextField(null=True)),
                ('public_result', models.TextField(null=True)),
            ],
        ),
    ]
