# Generated by Django 4.0.3 on 2022-03-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='ordering',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
