# Generated by Django 4.0.3 on 2022-03-29 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_competition_ordering'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='ordering',
            new_name='descendent_ordering',
        ),
    ]
